name: Signal release for Updater

on:
    workflow_dispatch:

jobs:
    signal-update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: pnpm

            - name: Create release.json
              run: pnpm release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
