name: Run UI Checks

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['16']

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: pnpm

            - name: Run type check
              run: pnpm run tsc:check

            - name: Run lint check
              run: pnpm run lint:check

            # - name: Run tests
            #   run: pnpm test
